// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	ID          int32
	TotalRating int32
	ReviewCount int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Refresh struct {
	ID        uuid.UUID
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Review struct {
	ID        int32
	MovieID   int32
	UserID    int32
	Title     string
	Rating    int32
	Review    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Username  string
	Email     string
	AvatarUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Watchlist struct {
	UserID    int32
	MovieID   int32
	Watched   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
