// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRefresh = `-- name: CreateRefresh :exec
INSERT INTO refresh (id, user_id)
VALUES ($1, $2)
`

type CreateRefreshParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) CreateRefresh(ctx context.Context, arg CreateRefreshParams) error {
	_, err := q.db.Exec(ctx, createRefresh, arg.ID, arg.UserID)
	return err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (movie_id, user_id, rating, title, review)
VALUES ($1, $2, $3, $4, $5)
`

type CreateReviewParams struct {
	MovieID int32
	UserID  int32
	Rating  int32
	Title   string
	Review  string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.Exec(ctx, createReview,
		arg.MovieID,
		arg.UserID,
		arg.Rating,
		arg.Title,
		arg.Review,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, username, email, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Username  string
	Email     string
	AvatarUrl string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementMovieRating = `-- name: DecrementMovieRating :exec
UPDATE movies
    SET total_rating = movies.total_rating - $2,
    review_count = movies.review_count - 1
WHERE id = $1
`

type DecrementMovieRatingParams struct {
	ID     int32
	Rating int32
}

func (q *Queries) DecrementMovieRating(ctx context.Context, arg DecrementMovieRatingParams) error {
	_, err := q.db.Exec(ctx, decrementMovieRating, arg.ID, arg.Rating)
	return err
}

const deleteRefresh = `-- name: DeleteRefresh :exec
DELETE FROM refresh
WHERE id = $1
`

func (q *Queries) DeleteRefresh(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefresh, id)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const incrementMovieRating = `-- name: IncrementMovieRating :exec
INSERT INTO movies (id, total_rating, review_count)
VALUES ($1, $2, 1)
    ON CONFLICT (id) DO UPDATE
    SET total_rating = movies.total_rating + $2,
    review_count = movies.review_count + 1
`

type IncrementMovieRatingParams struct {
	ID     int32
	Rating int32
}

func (q *Queries) IncrementMovieRating(ctx context.Context, arg IncrementMovieRatingParams) error {
	_, err := q.db.Exec(ctx, incrementMovieRating, arg.ID, arg.Rating)
	return err
}

const readMovie = `-- name: ReadMovie :one
SELECT id, total_rating, review_count, created_at, updated_at FROM movies
WHERE id = $1
`

func (q *Queries) ReadMovie(ctx context.Context, id int32) (Movie, error) {
	row := q.db.QueryRow(ctx, readMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TotalRating,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readRefresh = `-- name: ReadRefresh :one
SELECT r.id, r.user_id, r.created_at, r.updated_at, u.id, u.username, u.email, u.avatar_url, u.created_at, u.updated_at
FROM refresh r
JOIN users u ON r.user_id = u.id
WHERE r.id = $1
`

type ReadRefreshRow struct {
	Refresh Refresh
	User    User
}

func (q *Queries) ReadRefresh(ctx context.Context, id uuid.UUID) (ReadRefreshRow, error) {
	row := q.db.QueryRow(ctx, readRefresh, id)
	var i ReadRefreshRow
	err := row.Scan(
		&i.Refresh.ID,
		&i.Refresh.UserID,
		&i.Refresh.CreatedAt,
		&i.Refresh.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const readReview = `-- name: ReadReview :one
SELECT reviews.id, reviews.movie_id, reviews.user_id, reviews.title, reviews.rating, reviews.review, reviews.created_at, reviews.updated_at, users.id, users.username, users.email, users.avatar_url, users.created_at, users.updated_at
FROM reviews
JOIN users ON reviews.user_id = users.id
WHERE reviews.id = $1
`

type ReadReviewRow struct {
	Review Review
	User   User
}

func (q *Queries) ReadReview(ctx context.Context, id int32) (ReadReviewRow, error) {
	row := q.db.QueryRow(ctx, readReview, id)
	var i ReadReviewRow
	err := row.Scan(
		&i.Review.ID,
		&i.Review.MovieID,
		&i.Review.UserID,
		&i.Review.Title,
		&i.Review.Rating,
		&i.Review.Review,
		&i.Review.CreatedAt,
		&i.Review.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const readReviews = `-- name: ReadReviews :many
SELECT reviews.id, reviews.movie_id, reviews.user_id, reviews.title, reviews.rating, reviews.review, reviews.created_at, reviews.updated_at, users.id, users.username, users.email, users.avatar_url, users.created_at, users.updated_at
FROM reviews
JOIN users ON reviews.user_id = users.id
WHERE reviews.movie_id = $1
ORDER BY reviews.updated_at DESC
LIMIT $2 OFFSET $3
`

type ReadReviewsParams struct {
	MovieID int32
	Limit   int32
	Offset  int32
}

type ReadReviewsRow struct {
	Review Review
	User   User
}

func (q *Queries) ReadReviews(ctx context.Context, arg ReadReviewsParams) ([]ReadReviewsRow, error) {
	rows, err := q.db.Query(ctx, readReviews, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadReviewsRow
	for rows.Next() {
		var i ReadReviewsRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.MovieID,
			&i.Review.UserID,
			&i.Review.Title,
			&i.Review.Rating,
			&i.Review.Review,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readUser = `-- name: ReadUser :one
SELECT id, username, email, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) ReadUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, readUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserByEmail = `-- name: ReadUserByEmail :one
SELECT id, username, email, avatar_url, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) ReadUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, readUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserReview = `-- name: ReadUserReview :one
SELECT reviews.id, reviews.movie_id, reviews.user_id, reviews.title, reviews.rating, reviews.review, reviews.created_at, reviews.updated_at, users.id, users.username, users.email, users.avatar_url, users.created_at, users.updated_at
FROM reviews
JOIN users ON reviews.user_id = users.id
WHERE reviews.movie_id = $1 AND reviews.user_id = $2
`

type ReadUserReviewParams struct {
	MovieID int32
	UserID  int32
}

type ReadUserReviewRow struct {
	Review Review
	User   User
}

func (q *Queries) ReadUserReview(ctx context.Context, arg ReadUserReviewParams) (ReadUserReviewRow, error) {
	row := q.db.QueryRow(ctx, readUserReview, arg.MovieID, arg.UserID)
	var i ReadUserReviewRow
	err := row.Scan(
		&i.Review.ID,
		&i.Review.MovieID,
		&i.Review.UserID,
		&i.Review.Title,
		&i.Review.Rating,
		&i.Review.Review,
		&i.Review.CreatedAt,
		&i.Review.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const updateMovieRating = `-- name: UpdateMovieRating :exec
UPDATE movies
SET total_rating = total_rating - $2 + $3
WHERE id = $1
`

type UpdateMovieRatingParams struct {
	ID        int32
	OldRating int32
	NewRating int32
}

func (q *Queries) UpdateMovieRating(ctx context.Context, arg UpdateMovieRatingParams) error {
	_, err := q.db.Exec(ctx, updateMovieRating, arg.ID, arg.OldRating, arg.NewRating)
	return err
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET title = $2, rating = $3, review = $4
FROM users
WHERE reviews.id = $1
RETURNING reviews.id, reviews.movie_id, reviews.user_id, reviews.title, reviews.rating, reviews.review, reviews.created_at, reviews.updated_at, users.id, users.username, users.email, users.avatar_url, users.created_at, users.updated_at
`

type UpdateReviewParams struct {
	ID     int32
	Title  string
	Rating int32
	Review string
}

type UpdateReviewRow struct {
	Review Review
	User   User
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (UpdateReviewRow, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.ID,
		arg.Title,
		arg.Rating,
		arg.Review,
	)
	var i UpdateReviewRow
	err := row.Scan(
		&i.Review.ID,
		&i.Review.MovieID,
		&i.Review.UserID,
		&i.Review.Title,
		&i.Review.Rating,
		&i.Review.Review,
		&i.Review.CreatedAt,
		&i.Review.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}
